#!/bin/bash
# Auto-generated by mirror install-daemon. Do not edit.
cd "/Users/user/github-notion-mirror"
set -a
source .env
set +a
exec "/opt/homebrew/bin/bun" "/Users/user/github-notion-mirror/src/index.ts" serve
