import { existsSync, mkdirSync, writeFileSync, readFileSync, unlinkSync, statSync } from "node:fs";
import { resolve, join } from "node:path";
import { execSync } from "node:child_process";
import { logger } from "../logging.ts";

// launchd daemon installer for macOS.
// Generates a LaunchAgent plist + start.sh wrapper that loads .env and runs bun serve.
// ponytail: user-level LaunchAgent (no sudo needed), KeepAlive=true, RunAtLoad=true.
// Ceiling: systemd unit for Linux; launchd plist for org-level daemon if needed.

const LABEL = "com.kartikkabadi.github-notion-mirror";
const LAUNCH_AGENTS_DIR = resolve(process.env.HOME ?? "~", "Library/LaunchAgents");
const LOG_DIR = resolve(process.env.HOME ?? "~", "Library/Logs/github-notion-mirror");
const PLIST_PATH = join(LAUNCH_AGENTS_DIR, `${LABEL}.plist`);
const START_SCRIPT = resolve(process.cwd(), "start-daemon.sh");

export async function installDaemonCommand(): Promise<void> {
  const repoRoot = process.cwd();

  // 1. Verify bun is available
  const bunPath = execSync("which bun", { encoding: "utf8" }).trim();
  if (!bunPath) {
    console.error("bun not found on PATH. Install Bun first.");
    process.exit(1);
  }

  // 2. Verify .env exists
  if (!existsSync(resolve(repoRoot, ".env"))) {
    console.error(".env not found. Run `cp .env.example .env` and fill values first.");
    process.exit(1);
  }

  // 3. Create log directory
  mkdirSync(LOG_DIR, { recursive: true });

  // 4. Generate start-daemon.sh wrapper (loads .env, cds to repo, execs bun serve)
  const startScript = `#!/bin/bash
# Auto-generated by mirror install-daemon. Do not edit.
cd "${repoRoot}"
set -a
source .env
set +a
exec "${bunPath}" "${resolve(repoRoot, "src/index.ts")}" serve
`;
  writeFileSync(START_SCRIPT, startScript, { mode: 0o700 });
  console.log(`Created ${START_SCRIPT} (chmod 700)`);

  // 5. Generate plist
  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${START_SCRIPT}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${repoRoot}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${join(LOG_DIR, "daemon.log")}</string>
  <key>StandardErrorPath</key>
  <string>${join(LOG_DIR, "daemon.err")}</string>
</dict>
</plist>
`;

  mkdirSync(LAUNCH_AGENTS_DIR, { recursive: true });
  writeFileSync(PLIST_PATH, plist, { mode: 0o644 });
  console.log(`Created ${PLIST_PATH}`);

  // 6. Bootstrap the agent
  try {
    execSync(`launchctl bootout gui/$(id -u) ${PLIST_PATH} 2>/dev/null || true`);
    execSync(`launchctl bootstrap gui/$(id -u) ${PLIST_PATH}`);
    console.log("Daemon loaded via launchctl.");
  } catch (err) {
    console.error(`Failed to bootstrap daemon: ${(err as Error).message}`);
    console.error(`Try manually: launchctl bootstrap gui/$(id -u) ${PLIST_PATH}`);
  }

  console.log("\nDaemon installed. It will:");
  console.log("  - Start automatically on login (RunAtLoad)");
  console.log("  - Restart if it crashes (KeepAlive)");
  console.log(`  - Log to ${LOG_DIR}/daemon.log and daemon.err`);
  console.log("\nManage with:");
  console.log("  mirror daemon-status    # check if running");
  console.log("  mirror uninstall-daemon  # remove");
  console.log("  tail -f ~/Library/Logs/github-notion-mirror/daemon.log  # watch logs");
}

export async function uninstallDaemonCommand(): Promise<void> {
  // 1. Bootout the agent
  try {
    execSync(`launchctl bootout gui/$(id -u) ${PLIST_PATH} 2>/dev/null || true`);
    console.log("Daemon stopped via launchctl.");
  } catch {
    console.log("Daemon was not loaded (or already stopped).");
  }

  // 2. Remove plist
  if (existsSync(PLIST_PATH)) {
    unlinkSync(PLIST_PATH);
    console.log(`Removed ${PLIST_PATH}`);
  }

  // 3. Remove start script
  if (existsSync(START_SCRIPT)) {
    unlinkSync(START_SCRIPT);
    console.log(`Removed ${START_SCRIPT}`);
  }

  console.log("Daemon uninstalled.");
}

export async function daemonStatusCommand(): Promise<void> {
  const plistExists = existsSync(PLIST_PATH);
  const startExists = existsSync(START_SCRIPT);
  const logExists = existsSync(join(LOG_DIR, "daemon.log"));

  console.log("Daemon status:\n");
  console.log(`  plist:     ${plistExists ? "exists" : "missing"} — ${PLIST_PATH}`);
  console.log(`  start.sh:  ${startExists ? "exists" : "missing"} — ${START_SCRIPT}`);
  console.log(`  log dir:   ${logExists ? "has logs" : "no logs yet"} — ${LOG_DIR}`);

  // Check if launchd has it loaded
  let loaded = false;
  let pid: string | null = null;
  try {
    const out = execSync(`launchctl print gui/$(id -u)/${LABEL} 2>&1`, { encoding: "utf8" });
    loaded = !out.includes("Could not find service");
    const pidMatch = out.match(/pid = (\d+)/);
    pid = pidMatch?.[1] ?? null;
  } catch {
    loaded = false;
  }

  console.log(`  loaded:    ${loaded ? "yes" : "no"}`);
  if (pid) console.log(`  pid:       ${pid}`);

  // Check log freshness
  if (logExists) {
    try {
      const stat = statSync(join(LOG_DIR, "daemon.log"));
      const ageMin = Math.round((Date.now() - stat.mtimeMs) / 60000);
      console.log(`  last log:  ${ageMin}m ago`);
    } catch { /* ignore */ }
  }

  if (!plistExists) {
    console.log("\nDaemon not installed. Run `mirror install-daemon`.");
  } else if (!loaded) {
    console.log("\nPlist exists but daemon not loaded. Run `mirror install-daemon` to reload.");
  } else {
    console.log("\nDaemon is running.");
  }
}

export function daemonChecks(): { name: string; ok: boolean; detail: string }[] {
  const checks: { name: string; ok: boolean; detail: string }[] = [];
  const plistExists = existsSync(PLIST_PATH);
  checks.push({
    name: "daemon plist",
    ok: plistExists,
    detail: plistExists ? "installed" : "not installed — run mirror install-daemon",
  });

  if (plistExists) {
    try {
      const out = execSync(`launchctl print gui/$(id -u)/${LABEL} 2>&1`, { encoding: "utf8" });
      const loaded = !out.includes("Could not find service");
      checks.push({
        name: "daemon loaded",
        ok: loaded,
        detail: loaded ? "running" : "not loaded — run mirror install-daemon",
      });
    } catch {
      checks.push({ name: "daemon loaded", ok: false, detail: "not loaded" });
    }
  }

  return checks;
}
